# Generated by Django 5.0.2 on 2024-02-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceDucksData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TextField()),
                ('updated_at', models.TextField()),
                ('event_type', models.IntegerField()),
                ('payload', models.TextField()),
                ('device_id', models.TextField()),
                ('uuid', models.TextField()),
                ('device_type', models.TextField()),
                ('company_id', models.TextField()),
            ],
            options={
                'db_table': 'SpaceDucksData',
            },
        ),
    ]
